#name: Daily health check

#on:
#  schedule:
#    - cron: "0 0 * * *"
#  workflow_dispatch:

#jobs:
#  health_check:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Verify service availability with pings
#        uses: jtalk/url-health-check-action@v4
#        with:
#          url: https://fullstackopen-cicd.onrender.com/
#          max-attempts: 3
#          retry-delay: 20s
